### ISSUE TITLE
some issues about your image

### ISSUE THREAD

**Issue by AdamZeng1** [huangrt01/CS-Notes#2]
I find there are some images that couldn't be displayed normally. Could you check that?

**Comment by huangruiteng** [comment]
有两种可能：
1）github网络不好，图无法在网页显示
2）我用到的[md笔记转换器](https://github.com/huangrt01/Markdown-Transformer-and-Uploader)有bug，里面处理latex公式的逻辑，会把shell script中存在$$的部分也转化成图片，这导致网页多显示一些不存在的图片。这个我暂时没时间修。

解决方案：
1）clone仓库，用md阅读器，看Notes里的文档
2）修md转换器的bug
